server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  application:
    name: traffic-management-system
  
  datasource:
    url: jdbc:h2:mem:trafficdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds

# Google Maps API Configuration
google:
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY:your-api-key-here}

# ML Model Configuration
ml:
  model:
    endpoint: ${ML_MODEL_ENDPOINT:http://localhost:5000/predict}
    timeout: 5000

# Traffic Data Configuration
traffic:
  data:
    retention-days: 30
    batch-size: 100

# Logging Configuration
logging:
  level:
    com.traffic: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    config-url: /api/v1/api-docs/swagger-config
    url: /api/v1/api-docs
